apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-demo-app
  namespace: argocd
  annotations:
    # ArgoCD Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: app=docker.io/pranathinallamilli/java-demo-app
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^main-[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/app.pull-secret: pullsecret:argocd/dockerhub-creds
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/pranathi-nallamilli/CRD-POC.git
    targetRevision: HEAD
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
