apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-cosign-signatures
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-image-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "docker.io/pranathinallamilli/java-demo-app:*"
          mutateDigest: false
          verifyDigest: false
          imageRegistryCredentials:
            secrets:
              - docker-hub-creds
              - docker-hub-creds-v2
            allowInsecureRegistry: false
          attestors:
            - entries:
                - keys:
                    publicKeys: |
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfSlrOWJhsOUTGDliURCh2hIGGLlT
                      RCG9olKgiRrHKjH6muJzyYIpDmniYEJGUxVNeDxWZVIOgBHoPRR7ULuzNw==
                      -----END PUBLIC KEY-----
